[package]
name = "redra"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.*"
nalgebra = "0.*"
prost = "0.*"
socket2 = "0.*"
tokio = { version = "1.*", features = ["rt-multi-thread", "sync"] }

[build-dependencies]
prost-build = "0.*"