[package]
name = "redra"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.*"
log = "0.*"
nalgebra = "0.*"
prost = "0.*"
ringbuf = "0.*"
smooth-bevy-cameras = { git = "https://github.com/vesita/smooth-bevy-cameras.git" }
tokio = { version = "1.*", features = ["full"] }

[build-dependencies]
prost-build = "0.*"
