[package]
name = "redra"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.*", optional = true }
log = "0.*"
nalgebra = "0.*"
prost = "0.*"
ringbuf = "0.*"
tokio = { version = "1.*", features = ["full"] }
approx = "0.*"
serde = { version = "1.*", optional = true }
bevy_egui = { version = "0.*", optional = true }

[build-dependencies]
prost-build = "0.*"

[features]
default = ["exec"]
exec = ["graph"]
client = []
graph = ["dep:bevy", "dep:bevy_egui"]