[project]
name = "redra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "build>=1.3.0",
    "numpy>=2.4.0",
    "protobuf>=6.33.2",
]
